"""catalogo_comercial_compras_historico

Revision ID: 0f6af4c60f80
Revises: 91ae81c71007
Create Date: 2026-10-07 11:42:49.806003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0f6af4c60f80'
down_revision: Union[str, None] = '91ae81c71007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('revisao', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_compra_tenant_id'), 'fornecedores_compra', ['tenant_id'], unique=False)
    op.create_index('uq_fornecedores_compra_cnpj_ativo', 'fornecedores_compra', ['tenant_id', 'cnpj'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND cnpj IS NOT NULL'))
    op.create_table('compras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chave', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_nome_snapshot', sa.String(length=200), nullable=True),
    sa.Column('estabelecimento_original', sa.String(length=200), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('identidade_nota', sa.String(length=44), nullable=True),
    sa.Column('total_nota', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_selecionado', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('metadados_completos', sa.Boolean(), nullable=False),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores_compra.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chave')
    )
    op.create_index(op.f('ix_compras_data_compra'), 'compras', ['data_compra'], unique=False)
    op.create_index(op.f('ix_compras_fornecedor_id'), 'compras', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_compras_identidade_nota'), 'compras', ['identidade_nota'], unique=False)
    op.create_index(op.f('ix_compras_tenant_id'), 'compras', ['tenant_id'], unique=False)
    op.create_table('produtos_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=200), nullable=False),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('variante', sa.String(length=200), nullable=True),
    sa.Column('conteudo_embalagem', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('unidade_conteudo', sa.String(length=40), nullable=False),
    sa.Column('fator_para_principal', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('revisao', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_compra_ingrediente_id'), 'produtos_compra', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_produtos_compra_tenant_id'), 'produtos_compra', ['tenant_id'], unique=False)
    op.create_index('uq_produtos_compra_gtin_ativo', 'produtos_compra', ['tenant_id', 'gtin'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND gtin IS NOT NULL'))
    op.create_table('aliases_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor_original', sa.String(length=500), nullable=False),
    sa.Column('valor_normalizado', sa.String(length=500), nullable=False),
    sa.Column('revisao', sa.Integer(), nullable=False),
    sa.Column('produto_revisao_confirmada', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores_compra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_compra.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliases_compra_fornecedor_id'), 'aliases_compra', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_aliases_compra_produto_id'), 'aliases_compra', ['produto_id'], unique=False)
    op.create_index(op.f('ix_aliases_compra_tenant_id'), 'aliases_compra', ['tenant_id'], unique=False)
    op.create_index('uq_aliases_compra_ativo', 'aliases_compra', ['tenant_id', 'fornecedor_id', 'tipo', 'valor_normalizado'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('aprovacoes_fornecedor_produto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores_compra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_compra.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fornecedor_id', 'produto_id')
    )
    op.create_index(op.f('ix_aprovacoes_fornecedor_produto_fornecedor_id'), 'aprovacoes_fornecedor_produto', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_aprovacoes_fornecedor_produto_produto_id'), 'aprovacoes_fornecedor_produto', ['produto_id'], unique=False)
    op.create_index(op.f('ix_aprovacoes_fornecedor_produto_tenant_id'), 'aprovacoes_fornecedor_produto', ['tenant_id'], unique=False)
    op.create_table('compra_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compra_id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('movimentacao_id', sa.UUID(), nullable=False),
    sa.Column('indice', sa.Integer(), nullable=False),
    sa.Column('quantidade_principal', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('custo_normalizado', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('preco_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos_compra.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimentacao_id')
    )
    op.create_index(op.f('ix_compra_itens_compra_id'), 'compra_itens', ['compra_id'], unique=False)
    op.create_index(op.f('ix_compra_itens_ingrediente_id'), 'compra_itens', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_compra_itens_produto_id'), 'compra_itens', ['produto_id'], unique=False)
    op.create_index(op.f('ix_compra_itens_tenant_id'), 'compra_itens', ['tenant_id'], unique=False)
    op.add_column('whatsapp_compras', sa.Column('contexto', postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_compras', 'contexto')
    op.drop_index(op.f('ix_compra_itens_tenant_id'), table_name='compra_itens')
    op.drop_index(op.f('ix_compra_itens_produto_id'), table_name='compra_itens')
    op.drop_index(op.f('ix_compra_itens_ingrediente_id'), table_name='compra_itens')
    op.drop_index(op.f('ix_compra_itens_compra_id'), table_name='compra_itens')
    op.drop_table('compra_itens')
    op.drop_index(op.f('ix_aprovacoes_fornecedor_produto_tenant_id'), table_name='aprovacoes_fornecedor_produto')
    op.drop_index(op.f('ix_aprovacoes_fornecedor_produto_produto_id'), table_name='aprovacoes_fornecedor_produto')
    op.drop_index(op.f('ix_aprovacoes_fornecedor_produto_fornecedor_id'), table_name='aprovacoes_fornecedor_produto')
    op.drop_table('aprovacoes_fornecedor_produto')
    op.drop_index('uq_aliases_compra_ativo', table_name='aliases_compra', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_aliases_compra_tenant_id'), table_name='aliases_compra')
    op.drop_index(op.f('ix_aliases_compra_produto_id'), table_name='aliases_compra')
    op.drop_index(op.f('ix_aliases_compra_fornecedor_id'), table_name='aliases_compra')
    op.drop_table('aliases_compra')
    op.drop_index('uq_produtos_compra_gtin_ativo', table_name='produtos_compra', postgresql_where=sa.text('deleted_at IS NULL AND gtin IS NOT NULL'))
    op.drop_index(op.f('ix_produtos_compra_tenant_id'), table_name='produtos_compra')
    op.drop_index(op.f('ix_produtos_compra_ingrediente_id'), table_name='produtos_compra')
    op.drop_table('produtos_compra')
    op.drop_index(op.f('ix_compras_tenant_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_identidade_nota'), table_name='compras')
    op.drop_index(op.f('ix_compras_fornecedor_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_data_compra'), table_name='compras')
    op.drop_table('compras')
    op.drop_index('uq_fornecedores_compra_cnpj_ativo', table_name='fornecedores_compra', postgresql_where=sa.text('deleted_at IS NULL AND cnpj IS NOT NULL'))
    op.drop_index(op.f('ix_fornecedores_compra_tenant_id'), table_name='fornecedores_compra')
    op.drop_table('fornecedores_compra')
    # ### end Alembic commands ###
