"""ingrediente_codigo_tipo_saldo_receita_modo_preparo

Revision ID: 185300842957
Revises: f9580e171420
Create Date: 2026-05-28 13:14:44.185577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '185300842957'
down_revision: Union[str, None] = 'f9580e171420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adiciona colunas em duas etapas para preservar linhas existentes:
    # 1. Cria nullable; 2. Popula com defaults; 3. Aplica NOT NULL.

    # ----- ingredientes.tipo -----
    op.add_column('ingredientes', sa.Column('tipo', sa.String(length=30), nullable=True))
    op.execute("UPDATE ingredientes SET tipo = 'ingrediente' WHERE tipo IS NULL")
    op.alter_column('ingredientes', 'tipo', nullable=False)
    op.create_index(op.f('ix_ingredientes_tipo'), 'ingredientes', ['tipo'], unique=False)

    # ----- ingredientes.quantidade_reservada -----
    op.add_column(
        'ingredientes',
        sa.Column('quantidade_reservada', sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.execute("UPDATE ingredientes SET quantidade_reservada = 0 WHERE quantidade_reservada IS NULL")
    op.alter_column('ingredientes', 'quantidade_reservada', nullable=False)

    # ----- ingredientes.data_custo_atualizado (nullable, ok) -----
    op.add_column(
        'ingredientes',
        sa.Column('data_custo_atualizado', sa.DateTime(timezone=True), nullable=True),
    )
    # Para registros existentes assume que o custo atual reflete a última entrada
    op.execute(
        "UPDATE ingredientes SET data_custo_atualizado = updated_at "
        "WHERE data_custo_atualizado IS NULL AND custo_medio > 0"
    )

    # ----- ingredientes.codigo (sequencial por tenant) -----
    op.add_column('ingredientes', sa.Column('codigo', sa.Integer(), nullable=True))
    # Atribui códigos 1..N por ordem de criação dentro de cada tenant
    op.execute(
        """
        WITH numerados AS (
          SELECT id, ROW_NUMBER() OVER (PARTITION BY tenant_id ORDER BY created_at) AS rn
          FROM ingredientes
        )
        UPDATE ingredientes SET codigo = numerados.rn
        FROM numerados WHERE ingredientes.id = numerados.id
        """
    )
    op.alter_column('ingredientes', 'codigo', nullable=False)
    op.create_index(op.f('ix_ingredientes_codigo'), 'ingredientes', ['codigo'], unique=False)

    # ----- receitas.modo_preparo (nullable, ok direto) -----
    op.add_column('receitas', sa.Column('modo_preparo', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receitas', 'modo_preparo')
    op.drop_index(op.f('ix_ingredientes_tipo'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_codigo'), table_name='ingredientes')
    op.drop_column('ingredientes', 'data_custo_atualizado')
    op.drop_column('ingredientes', 'quantidade_reservada')
    op.drop_column('ingredientes', 'tipo')
    op.drop_column('ingredientes', 'codigo')
    # ### end Alembic commands ###
