"""schema_inicial

Revision ID: 22acf6da34f7
Revises: 
Create Date: 2026-05-28 11:33:13.830903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22acf6da34f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes_custo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custo_operacional_mensal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('horas_mensais', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_custo_tenant_id'), 'configuracoes_custo', ['tenant_id'], unique=False)
    op.create_table('ingredientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('estoque_atual', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_nome'), 'ingredientes', ['nome'], unique=False)
    op.create_index(op.f('ix_ingredientes_tenant_id'), 'ingredientes', ['tenant_id'], unique=False)
    op.create_table('receitas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('rendimento', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('rendimento_unidade', sa.String(length=50), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('margem_desejada', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receitas_nome'), 'receitas', ['nome'], unique=False)
    op.create_index(op.f('ix_receitas_tenant_id'), 'receitas', ['tenant_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('valor_hora', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_tenant_id'), 'usuarios', ['tenant_id'], unique=False)
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_estoque_ingrediente_id'), 'movimentacoes_estoque', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_tenant_id'), 'movimentacoes_estoque', ['tenant_id'], unique=False)
    op.create_table('receita_etapas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receita_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('tipo_mao_obra', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receita_etapas_receita_id'), 'receita_etapas', ['receita_id'], unique=False)
    op.create_table('receita_ingredientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receita_id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receita_ingredientes_receita_id'), 'receita_ingredientes', ['receita_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receita_ingredientes_receita_id'), table_name='receita_ingredientes')
    op.drop_table('receita_ingredientes')
    op.drop_index(op.f('ix_receita_etapas_receita_id'), table_name='receita_etapas')
    op.drop_table('receita_etapas')
    op.drop_index(op.f('ix_movimentacoes_estoque_tenant_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_ingrediente_id'), table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    op.drop_index(op.f('ix_usuarios_tenant_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_receitas_tenant_id'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_nome'), table_name='receitas')
    op.drop_table('receitas')
    op.drop_index(op.f('ix_ingredientes_tenant_id'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_nome'), table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_index(op.f('ix_configuracoes_custo_tenant_id'), table_name='configuracoes_custo')
    op.drop_table('configuracoes_custo')
    op.drop_table('tenants')
    # ### end Alembic commands ###
