"""etapas_preparo_tempo_pendente

Revision ID: 2798d1537c70
Revises: 7b6ef690c202
Create Date: 2026-10-06 14:24:09.553527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2798d1537c70'
down_revision: Union[str, None] = '7b6ef690c202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapas_padrao', sa.Column('instrucao', sa.Text(), nullable=True))
    op.add_column('etapas_padrao', sa.Column('receita_origem', sa.String(length=300), nullable=True))
    op.alter_column('etapas_padrao', 'duracao_minutos_default',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etapas_padrao', 'duracao_minutos_default',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('etapas_padrao', 'receita_origem')
    op.drop_column('etapas_padrao', 'instrucao')
    # ### end Alembic commands ###
