"""agenda_itens

Revision ID: 4d4eb7c39e35
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 13:40:38.762434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d4eb7c39e35'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('receita_id', sa.UUID(), nullable=True),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('ordem_producao_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ordem_producao_id'], ['ordens_producao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_itens_data'), 'agenda_itens', ['data'], unique=False)
    op.create_index(op.f('ix_agenda_itens_tenant_id'), 'agenda_itens', ['tenant_id'], unique=False)
    # Índice composto: as queries principais filtram por tenant + range de datas.
    op.create_index(
        'ix_agenda_itens_tenant_data', 'agenda_itens', ['tenant_id', 'data'], unique=False
    )
    # NOTE: o autogenerate sinalizou remoção de 'ux_estoque_pa_tenant_receita_ativo'
    # (índice único parcial criado via SQL bruto na migration a1b2c3d4e5f6, fora do
    # metadata do ORM). Não é uma mudança real — preservamos o índice intacto.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agenda_itens_tenant_data', table_name='agenda_itens')
    op.drop_index(op.f('ix_agenda_itens_tenant_id'), table_name='agenda_itens')
    op.drop_index(op.f('ix_agenda_itens_data'), table_name='agenda_itens')
    op.drop_table('agenda_itens')
    # ### end Alembic commands ###
