"""vendas

Revision ID: 5773d636139d
Revises: ff1a62e78ec2
Create Date: 2026-05-29 00:16:33.468461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5773d636139d'
down_revision: Union[str, None] = 'ff1a62e78ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('data_venda', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_canal'), 'vendas', ['canal'], unique=False)
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_data_venda'), 'vendas', ['data_venda'], unique=False)
    op.create_index(op.f('ix_vendas_numero'), 'vendas', ['numero'], unique=False)
    op.create_index(op.f('ix_vendas_tenant_id'), 'vendas', ['tenant_id'], unique=False)
    op.create_table('venda_itens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('receita_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_itens_tenant_id'), 'venda_itens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_venda_itens_venda_id'), 'venda_itens', ['venda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venda_itens_venda_id'), table_name='venda_itens')
    op.drop_index(op.f('ix_venda_itens_tenant_id'), table_name='venda_itens')
    op.drop_table('venda_itens')
    op.drop_index(op.f('ix_vendas_tenant_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_numero'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_data_venda'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_canal'), table_name='vendas')
    op.drop_table('vendas')
    # ### end Alembic commands ###
