"""composicao_estoque_intermediario

Revision ID: 756dcb38fc17
Revises: eb1a9dcd61f4
Create Date: 2026-10-06 11:16:02.270043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '756dcb38fc17'
down_revision: Union[str, None] = 'eb1a9dcd61f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque_produto_acabado', sa.Column('qtd_reservada', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.add_column('ordens_producao', sa.Column('ficha_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordens_producao', 'ficha_snapshot')
    op.drop_column('estoque_produto_acabado', 'qtd_reservada')
    # ### end Alembic commands ###
