"""unidades_alternativas_ingredientes

Revision ID: 7b6ef690c202
Revises: 6d0a753dbf1c
Create Date: 2026-10-06 14:18:19.825033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7b6ef690c202'
down_revision: Union[str, None] = '6d0a753dbf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('unidades_alternativas', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientes', 'unidades_alternativas')
    # ### end Alembic commands ###
