"""preco_de_venda_real_receita

Revision ID: 856e36600193
Revises: 185300842957
Create Date: 2026-05-28 21:41:46.346227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '856e36600193'
down_revision: Union[str, None] = '185300842957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('preco_de_venda_real', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receitas', 'preco_de_venda_real')
    # ### end Alembic commands ###
