"""estoque_produto_acabado

Revision ID: 9dd6076eb726
Revises: c6fa099c75ae
Create Date: 2026-05-29 00:07:12.157071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9dd6076eb726'
down_revision: Union[str, None] = 'c6fa099c75ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_produto_acabado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receita_id', sa.UUID(), nullable=False),
    sa.Column('qtd_disponivel', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qtd_minima', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_produto_acabado_receita_id'), 'estoque_produto_acabado', ['receita_id'], unique=False)
    op.create_index(op.f('ix_estoque_produto_acabado_tenant_id'), 'estoque_produto_acabado', ['tenant_id'], unique=False)
    op.create_table('movimentacoes_estoque_pa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receita_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_estoque_pa_receita_id'), 'movimentacoes_estoque_pa', ['receita_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_pa_tenant_id'), 'movimentacoes_estoque_pa', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_estoque_pa_tenant_id'), table_name='movimentacoes_estoque_pa')
    op.drop_index(op.f('ix_movimentacoes_estoque_pa_receita_id'), table_name='movimentacoes_estoque_pa')
    op.drop_table('movimentacoes_estoque_pa')
    op.drop_index(op.f('ix_estoque_produto_acabado_tenant_id'), table_name='estoque_produto_acabado')
    op.drop_index(op.f('ix_estoque_produto_acabado_receita_id'), table_name='estoque_produto_acabado')
    op.drop_table('estoque_produto_acabado')
    # ### end Alembic commands ###
