"""whatsapp_onboarding

Revision ID: a42f344c4565
Revises: 756dcb38fc17
Create Date: 2026-10-06 11:24:50.772981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a42f344c4565'
down_revision: Union[str, None] = '756dcb38fc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('endereco', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('usuarios', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.drop_column('usuarios', 'telefone')
    op.drop_column('tenants', 'endereco')
    # ### end Alembic commands ###
