"""ficha_tecnica_receita

Revision ID: eb1a9dcd61f4
Revises: b1c2d3e4f5a6
Create Date: 2026-10-06 11:03:04.925246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eb1a9dcd61f4'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receitas', sa.Column('ficha_tecnica', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('receitas', sa.Column('ficha_revisao', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receitas', 'ficha_revisao')
    op.drop_column('receitas', 'ficha_tecnica')
    # ### end Alembic commands ###
