"""etapas_padrao

Revision ID: f9580e171420
Revises: 22acf6da34f7
Create Date: 2026-05-28 12:09:57.857594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9580e171420'
down_revision: Union[str, None] = '22acf6da34f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapas_padrao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_mao_obra', sa.String(length=20), nullable=False),
    sa.Column('duracao_minutos_default', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etapas_padrao_tenant_id'), 'etapas_padrao', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etapas_padrao_tenant_id'), table_name='etapas_padrao')
    op.drop_table('etapas_padrao')
    # ### end Alembic commands ###
