"""ordens_producao

Revision ID: ff1a62e78ec2
Revises: 9dd6076eb726
Create Date: 2026-05-29 00:13:04.873462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff1a62e78ec2'
down_revision: Union[str, None] = '9dd6076eb726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_producao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('qtd_planejada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qtd_produzida', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_producao_data_prevista'), 'ordens_producao', ['data_prevista'], unique=False)
    op.create_index(op.f('ix_ordens_producao_numero'), 'ordens_producao', ['numero'], unique=False)
    op.create_index(op.f('ix_ordens_producao_pedido_id'), 'ordens_producao', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_ordens_producao_receita_id'), 'ordens_producao', ['receita_id'], unique=False)
    op.create_index(op.f('ix_ordens_producao_status'), 'ordens_producao', ['status'], unique=False)
    op.create_index(op.f('ix_ordens_producao_tenant_id'), 'ordens_producao', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordens_producao_tenant_id'), table_name='ordens_producao')
    op.drop_index(op.f('ix_ordens_producao_status'), table_name='ordens_producao')
    op.drop_index(op.f('ix_ordens_producao_receita_id'), table_name='ordens_producao')
    op.drop_index(op.f('ix_ordens_producao_pedido_id'), table_name='ordens_producao')
    op.drop_index(op.f('ix_ordens_producao_numero'), table_name='ordens_producao')
    op.drop_index(op.f('ix_ordens_producao_data_prevista'), table_name='ordens_producao')
    op.drop_table('ordens_producao')
    # ### end Alembic commands ###
